// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: shepherd.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShepherdConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ignore is a set of Keys to ignore.
	// Must not be nil.
	Ignore map[uint64]bool `protobuf:"bytes,1,rep,name=ignore,proto3" json:"ignore,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Controls what candle producers get spawned. Duplicates are not checked.
	// Must be within [0, 2047] and ascending.
	Interval      []int32 `protobuf:"fixed32,2,rep,packed,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShepherdConfig) Reset() {
	*x = ShepherdConfig{}
	mi := &file_shepherd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShepherdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShepherdConfig) ProtoMessage() {}

func (x *ShepherdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shepherd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShepherdConfig.ProtoReflect.Descriptor instead.
func (*ShepherdConfig) Descriptor() ([]byte, []int) {
	return file_shepherd_proto_rawDescGZIP(), []int{0}
}

func (x *ShepherdConfig) GetIgnore() map[uint64]bool {
	if x != nil {
		return x.Ignore
	}
	return nil
}

func (x *ShepherdConfig) GetInterval() []int32 {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_shepherd_proto protoreflect.FileDescriptor

const file_shepherd_proto_rawDesc = "" +
	"\n" +
	"\x0eshepherd.proto\x12\x05proto\"\xa2\x01\n" +
	"\x0eShepherdConfig\x129\n" +
	"\x06ignore\x18\x01 \x03(\v2!.proto.ShepherdConfig.IgnoreEntryR\x06ignore\x12\x1a\n" +
	"\binterval\x18\x02 \x03(\x0fR\binterval\x1a9\n" +
	"\vIgnoreEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B2Z0github.com/ringboundio/chasm/daemon/proto;protob\x06proto3"

var (
	file_shepherd_proto_rawDescOnce sync.Once
	file_shepherd_proto_rawDescData []byte
)

func file_shepherd_proto_rawDescGZIP() []byte {
	file_shepherd_proto_rawDescOnce.Do(func() {
		file_shepherd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shepherd_proto_rawDesc), len(file_shepherd_proto_rawDesc)))
	})
	return file_shepherd_proto_rawDescData
}

var file_shepherd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shepherd_proto_goTypes = []any{
	(*ShepherdConfig)(nil), // 0: proto.ShepherdConfig
	nil,                    // 1: proto.ShepherdConfig.IgnoreEntry
}
var file_shepherd_proto_depIdxs = []int32{
	1, // 0: proto.ShepherdConfig.ignore:type_name -> proto.ShepherdConfig.IgnoreEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shepherd_proto_init() }
func file_shepherd_proto_init() {
	if File_shepherd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shepherd_proto_rawDesc), len(file_shepherd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shepherd_proto_goTypes,
		DependencyIndexes: file_shepherd_proto_depIdxs,
		MessageInfos:      file_shepherd_proto_msgTypes,
	}.Build()
	File_shepherd_proto = out.File
	file_shepherd_proto_goTypes = nil
	file_shepherd_proto_depIdxs = nil
}
