// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nil struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nil) Reset() {
	*x = Nil{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type BinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinInfo) Reset() {
	*x = BinInfo{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinInfo) ProtoMessage() {}

func (x *BinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinInfo.ProtoReflect.Descriptor instead.
func (*BinInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *BinInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BinInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hidden        bool                   `protobuf:"varint,1,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Id            *ID                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tag           *string                `protobuf:"bytes,4,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Config        []byte                 `protobuf:"bytes,5,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Report        []byte                 `protobuf:"bytes,6,opt,name=report,proto3,oneof" json:"report,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Filter) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Filter) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Filter) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *Filter) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Filter) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *Filter) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DaeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaeCount) Reset() {
	*x = DaeCount{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaeCount) ProtoMessage() {}

func (x *DaeCount) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaeCount.ProtoReflect.Descriptor instead.
func (*DaeCount) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *DaeCount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RepDaeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Daemon        []*DaeInfo             `protobuf:"bytes,1,rep,name=daemon,proto3" json:"daemon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepDaeInfo) Reset() {
	*x = RepDaeInfo{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepDaeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepDaeInfo) ProtoMessage() {}

func (x *RepDaeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepDaeInfo.ProtoReflect.Descriptor instead.
func (*RepDaeInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RepDaeInfo) GetDaemon() []*DaeInfo {
	if x != nil {
		return x.Daemon
	}
	return nil
}

type DaeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *ID                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Config        []byte                 `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Report        []byte                 `protobuf:"bytes,5,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaeInfo) Reset() {
	*x = DaeInfo{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaeInfo) ProtoMessage() {}

func (x *DaeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaeInfo.ProtoReflect.Descriptor instead.
func (*DaeInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *DaeInfo) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DaeInfo) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DaeInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DaeInfo) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DaeInfo) GetReport() []byte {
	if x != nil {
		return x.Report
	}
	return nil
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint64                 `protobuf:"fixed64,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint64                 `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ID) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *ID) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"fixed64,1,opt,name=code,proto3" json:"code,omitempty"`
	Since         int64                  `protobuf:"fixed64,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *Status) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05proto\"\x05\n" +
	"\x03Nil\"5\n" +
	"\aBinInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xfc\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06hidden\x18\x01 \x01(\bR\x06hidden\x12\x19\n" +
	"\x02id\x18\x02 \x01(\v2\t.proto.IDR\x02id\x12%\n" +
	"\x06status\x18\x03 \x01(\v2\r.proto.StatusR\x06status\x12\x15\n" +
	"\x03tag\x18\x04 \x01(\tH\x00R\x03tag\x88\x01\x01\x12\x1b\n" +
	"\x06config\x18\x05 \x01(\fH\x01R\x06config\x88\x01\x01\x12\x1b\n" +
	"\x06report\x18\x06 \x01(\fH\x02R\x06report\x88\x01\x01\x12\x1d\n" +
	"\apayload\x18\a \x01(\fH\x03R\apayload\x88\x01\x01B\x06\n" +
	"\x04_tagB\t\n" +
	"\a_configB\t\n" +
	"\a_reportB\n" +
	"\n" +
	"\b_payload\" \n" +
	"\bDaeCount\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x10R\x05total\"4\n" +
	"\n" +
	"RepDaeInfo\x12&\n" +
	"\x06daemon\x18\x01 \x03(\v2\x0e.proto.DaeInfoR\x06daemon\"\x8d\x01\n" +
	"\aDaeInfo\x12\x19\n" +
	"\x02id\x18\x01 \x01(\v2\t.proto.IDR\x02id\x12%\n" +
	"\x06status\x18\x02 \x01(\v2\r.proto.StatusR\x06status\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06config\x18\x04 \x01(\fR\x06config\x12\x16\n" +
	"\x06report\x18\x05 \x01(\fR\x06report\"*\n" +
	"\x02ID\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x06R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x06R\x04high\"2\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x10R\x04code\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x10R\x05since2\x91\x05\n" +
	"\x05Forge\x12'\n" +
	"\tAddSymbol\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12%\n" +
	"\aAddBook\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12'\n" +
	"\tAddCandle\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12&\n" +
	"\bAddTrade\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12)\n" +
	"\vAddSchedule\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12%\n" +
	"\aAddData\x12\x0e.proto.BinInfo\x1a\n" +
	".proto.Nil\x12$\n" +
	"\x05Alive\x12\n" +
	".proto.Nil\x1a\x0f.proto.DaeCount\x12.\n" +
	"\n" +
	"DaemonInfo\x12\r.proto.Filter\x1a\x11.proto.RepDaeInfo\x12\x1f\n" +
	"\x06Revive\x12\t.proto.ID\x1a\n" +
	".proto.Nil\x12\"\n" +
	"\x05Pause\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12#\n" +
	"\x06Resume\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12$\n" +
	"\aRestart\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12&\n" +
	"\tSetConfig\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12!\n" +
	"\x04Hide\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12!\n" +
	"\x04Show\x12\r.proto.Filter\x1a\n" +
	".proto.Nil\x12\x1d\n" +
	"\x04Kill\x12\t.proto.ID\x1a\n" +
	".proto.Nil\x12\"\n" +
	"\bShutdown\x12\n" +
	".proto.Nil\x1a\n" +
	".proto.NilB3Z1github.com/mattgonewild/chasm/service/proto;protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_proto_goTypes = []any{
	(*Nil)(nil),        // 0: proto.Nil
	(*BinInfo)(nil),    // 1: proto.BinInfo
	(*Filter)(nil),     // 2: proto.Filter
	(*DaeCount)(nil),   // 3: proto.DaeCount
	(*RepDaeInfo)(nil), // 4: proto.RepDaeInfo
	(*DaeInfo)(nil),    // 5: proto.DaeInfo
	(*ID)(nil),         // 6: proto.ID
	(*Status)(nil),     // 7: proto.Status
}
var file_service_proto_depIdxs = []int32{
	6,  // 0: proto.Filter.id:type_name -> proto.ID
	7,  // 1: proto.Filter.status:type_name -> proto.Status
	5,  // 2: proto.RepDaeInfo.daemon:type_name -> proto.DaeInfo
	6,  // 3: proto.DaeInfo.id:type_name -> proto.ID
	7,  // 4: proto.DaeInfo.status:type_name -> proto.Status
	1,  // 5: proto.Forge.AddSymbol:input_type -> proto.BinInfo
	1,  // 6: proto.Forge.AddBook:input_type -> proto.BinInfo
	1,  // 7: proto.Forge.AddCandle:input_type -> proto.BinInfo
	1,  // 8: proto.Forge.AddTrade:input_type -> proto.BinInfo
	1,  // 9: proto.Forge.AddSchedule:input_type -> proto.BinInfo
	1,  // 10: proto.Forge.AddData:input_type -> proto.BinInfo
	0,  // 11: proto.Forge.Alive:input_type -> proto.Nil
	2,  // 12: proto.Forge.DaemonInfo:input_type -> proto.Filter
	6,  // 13: proto.Forge.Revive:input_type -> proto.ID
	2,  // 14: proto.Forge.Pause:input_type -> proto.Filter
	2,  // 15: proto.Forge.Resume:input_type -> proto.Filter
	2,  // 16: proto.Forge.Restart:input_type -> proto.Filter
	2,  // 17: proto.Forge.SetConfig:input_type -> proto.Filter
	2,  // 18: proto.Forge.Hide:input_type -> proto.Filter
	2,  // 19: proto.Forge.Show:input_type -> proto.Filter
	6,  // 20: proto.Forge.Kill:input_type -> proto.ID
	0,  // 21: proto.Forge.Shutdown:input_type -> proto.Nil
	0,  // 22: proto.Forge.AddSymbol:output_type -> proto.Nil
	0,  // 23: proto.Forge.AddBook:output_type -> proto.Nil
	0,  // 24: proto.Forge.AddCandle:output_type -> proto.Nil
	0,  // 25: proto.Forge.AddTrade:output_type -> proto.Nil
	0,  // 26: proto.Forge.AddSchedule:output_type -> proto.Nil
	0,  // 27: proto.Forge.AddData:output_type -> proto.Nil
	3,  // 28: proto.Forge.Alive:output_type -> proto.DaeCount
	4,  // 29: proto.Forge.DaemonInfo:output_type -> proto.RepDaeInfo
	0,  // 30: proto.Forge.Revive:output_type -> proto.Nil
	0,  // 31: proto.Forge.Pause:output_type -> proto.Nil
	0,  // 32: proto.Forge.Resume:output_type -> proto.Nil
	0,  // 33: proto.Forge.Restart:output_type -> proto.Nil
	0,  // 34: proto.Forge.SetConfig:output_type -> proto.Nil
	0,  // 35: proto.Forge.Hide:output_type -> proto.Nil
	0,  // 36: proto.Forge.Show:output_type -> proto.Nil
	0,  // 37: proto.Forge.Kill:output_type -> proto.Nil
	0,  // 38: proto.Forge.Shutdown:output_type -> proto.Nil
	22, // [22:39] is the sub-list for method output_type
	5,  // [5:22] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
