// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Forge_AddSymbol_FullMethodName   = "/proto.Forge/AddSymbol"
	Forge_AddBook_FullMethodName     = "/proto.Forge/AddBook"
	Forge_AddCandle_FullMethodName   = "/proto.Forge/AddCandle"
	Forge_AddTrade_FullMethodName    = "/proto.Forge/AddTrade"
	Forge_AddSchedule_FullMethodName = "/proto.Forge/AddSchedule"
	Forge_AddData_FullMethodName     = "/proto.Forge/AddData"
	Forge_Alive_FullMethodName       = "/proto.Forge/Alive"
	Forge_DaemonInfo_FullMethodName  = "/proto.Forge/DaemonInfo"
	Forge_Revive_FullMethodName      = "/proto.Forge/Revive"
	Forge_Pause_FullMethodName       = "/proto.Forge/Pause"
	Forge_Resume_FullMethodName      = "/proto.Forge/Resume"
	Forge_Restart_FullMethodName     = "/proto.Forge/Restart"
	Forge_SetConfig_FullMethodName   = "/proto.Forge/SetConfig"
	Forge_Hide_FullMethodName        = "/proto.Forge/Hide"
	Forge_Show_FullMethodName        = "/proto.Forge/Show"
	Forge_Kill_FullMethodName        = "/proto.Forge/Kill"
	Forge_Shutdown_FullMethodName    = "/proto.Forge/Shutdown"
)

// ForgeClient is the client API for Forge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForgeClient interface {
	AddSymbol(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	AddBook(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	AddCandle(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	AddTrade(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	AddSchedule(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	AddData(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error)
	Alive(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*DaeCount, error)
	DaemonInfo(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*RepDaeInfo, error)
	Revive(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nil, error)
	Pause(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	Resume(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	Restart(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	SetConfig(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	Hide(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	Show(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error)
	Kill(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nil, error)
	Shutdown(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error)
}

type forgeClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeClient(cc grpc.ClientConnInterface) ForgeClient {
	return &forgeClient{cc}
}

func (c *forgeClient) AddSymbol(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) AddBook(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) AddCandle(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddCandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) AddTrade(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) AddSchedule(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) AddData(ctx context.Context, in *BinInfo, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_AddData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Alive(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*DaeCount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaeCount)
	err := c.cc.Invoke(ctx, Forge_Alive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) DaemonInfo(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*RepDaeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepDaeInfo)
	err := c.cc.Invoke(ctx, Forge_DaemonInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Revive(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Revive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Pause(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Resume(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Restart(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) SetConfig(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Hide(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Hide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Show(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Show_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Kill(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Kill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeClient) Shutdown(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Nil)
	err := c.cc.Invoke(ctx, Forge_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgeServer is the server API for Forge service.
// All implementations must embed UnimplementedForgeServer
// for forward compatibility.
type ForgeServer interface {
	AddSymbol(context.Context, *BinInfo) (*Nil, error)
	AddBook(context.Context, *BinInfo) (*Nil, error)
	AddCandle(context.Context, *BinInfo) (*Nil, error)
	AddTrade(context.Context, *BinInfo) (*Nil, error)
	AddSchedule(context.Context, *BinInfo) (*Nil, error)
	AddData(context.Context, *BinInfo) (*Nil, error)
	Alive(context.Context, *Nil) (*DaeCount, error)
	DaemonInfo(context.Context, *Filter) (*RepDaeInfo, error)
	Revive(context.Context, *ID) (*Nil, error)
	Pause(context.Context, *Filter) (*Nil, error)
	Resume(context.Context, *Filter) (*Nil, error)
	Restart(context.Context, *Filter) (*Nil, error)
	SetConfig(context.Context, *Filter) (*Nil, error)
	Hide(context.Context, *Filter) (*Nil, error)
	Show(context.Context, *Filter) (*Nil, error)
	Kill(context.Context, *ID) (*Nil, error)
	Shutdown(context.Context, *Nil) (*Nil, error)
	mustEmbedUnimplementedForgeServer()
}

// UnimplementedForgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgeServer struct{}

func (UnimplementedForgeServer) AddSymbol(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSymbol not implemented")
}
func (UnimplementedForgeServer) AddBook(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (UnimplementedForgeServer) AddCandle(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCandle not implemented")
}
func (UnimplementedForgeServer) AddTrade(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTrade not implemented")
}
func (UnimplementedForgeServer) AddSchedule(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSchedule not implemented")
}
func (UnimplementedForgeServer) AddData(context.Context, *BinInfo) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddData not implemented")
}
func (UnimplementedForgeServer) Alive(context.Context, *Nil) (*DaeCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alive not implemented")
}
func (UnimplementedForgeServer) DaemonInfo(context.Context, *Filter) (*RepDaeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DaemonInfo not implemented")
}
func (UnimplementedForgeServer) Revive(context.Context, *ID) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revive not implemented")
}
func (UnimplementedForgeServer) Pause(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedForgeServer) Resume(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedForgeServer) Restart(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedForgeServer) SetConfig(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedForgeServer) Hide(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hide not implemented")
}
func (UnimplementedForgeServer) Show(context.Context, *Filter) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedForgeServer) Kill(context.Context, *ID) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kill not implemented")
}
func (UnimplementedForgeServer) Shutdown(context.Context, *Nil) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedForgeServer) mustEmbedUnimplementedForgeServer() {}
func (UnimplementedForgeServer) testEmbeddedByValue()               {}

// UnsafeForgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgeServer will
// result in compilation errors.
type UnsafeForgeServer interface {
	mustEmbedUnimplementedForgeServer()
}

func RegisterForgeServer(s grpc.ServiceRegistrar, srv ForgeServer) {
	// If the following call pancis, it indicates UnimplementedForgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Forge_ServiceDesc, srv)
}

func _Forge_AddSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddSymbol(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddBook(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_AddCandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddCandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddCandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddCandle(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_AddTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddTrade(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_AddSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddSchedule(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_AddData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).AddData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_AddData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).AddData(ctx, req.(*BinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Alive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Alive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Alive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Alive(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_DaemonInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).DaemonInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_DaemonInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).DaemonInfo(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Revive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Revive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Revive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Revive(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Pause(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Resume(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Restart(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).SetConfig(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Hide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Hide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Hide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Hide(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Show(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Kill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Kill(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forge_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).Shutdown(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

// Forge_ServiceDesc is the grpc.ServiceDesc for Forge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Forge",
	HandlerType: (*ForgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSymbol",
			Handler:    _Forge_AddSymbol_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _Forge_AddBook_Handler,
		},
		{
			MethodName: "AddCandle",
			Handler:    _Forge_AddCandle_Handler,
		},
		{
			MethodName: "AddTrade",
			Handler:    _Forge_AddTrade_Handler,
		},
		{
			MethodName: "AddSchedule",
			Handler:    _Forge_AddSchedule_Handler,
		},
		{
			MethodName: "AddData",
			Handler:    _Forge_AddData_Handler,
		},
		{
			MethodName: "Alive",
			Handler:    _Forge_Alive_Handler,
		},
		{
			MethodName: "DaemonInfo",
			Handler:    _Forge_DaemonInfo_Handler,
		},
		{
			MethodName: "Revive",
			Handler:    _Forge_Revive_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _Forge_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _Forge_Resume_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _Forge_Restart_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Forge_SetConfig_Handler,
		},
		{
			MethodName: "Hide",
			Handler:    _Forge_Hide_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _Forge_Show_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Forge_Kill_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Forge_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
